### ISSUE TITLE
Add role/group based access management

### ISSUE THREAD

**Issue by gauthamsuresh09** [verloop/labelit#6]
Access to different parts of labelit should be controlled using group the user belongs to. We will have three groups mainly:

1. Admin : Admins manage the application, they have complete access to Admin panel. Basically this is Django admin user. Admins manage other users.
2. Managers : Managers are users who create and control label studio projects. They can use admin panel to create projects and assign annotators to projects. They will be given access only for editing previously mentioned data, nothing else.
3. Annotators : Annotators don't have access to admin panel. They can list their projects and go to respective project's labeling or tasks page.

**Comment by ashmeet13** [comment]
Thinking of this - 
Currently project creation is through the admin panel. 

1. Have a ViewSet for Project. (Access - Manager)
     - Create a project
     - Delete a project (Show only currently logged in manager's project)
     - Edit a project (Show only currently logged in manager's projects )

2. ViewSet to manage annotators (Access - Manager) (Projects of currently logged in manager)
     - Add 
     - Remove
